### ISSUE TITLE
ZeroDivisionError with default_epoch_optim_loop

### ISSUE THREAD

**Issue by jbueltemeier** [pmeier/pystiche#102]
I get an `ZeroDivisionError: integer division or modulo by zero` when using the `default_transformer_epoch_optim_loop`. This is probably because the `num_batches` of the `batch_sampler` is much smaller than in the `default_transformer_optim_loop` which results in `log_freq=0` in `default_transformer_optim_log_fn.` 

Below is a minimal example to reproduce the error: 
```python
from pystiche.optim.log import default_transformer_optim_log_fn, OptimLogger

logger = OptimLogger()
num_batches = 300
log_fn = default_transformer_optim_log_fn(logger, num_batches)
image_loading_velocity = 1
image_processing_velocity = 1
batch = 1
loss = 1
log_fn(batch, loss, image_loading_velocity, image_processing_velocity)
```

**Comment by pmeier** [comment]
You are right, 

https://github.com/pmeier/pystiche/blob/20816a6c5693cb30a0551d37c127d56bdccfd6d1/pystiche/optim/log.py#L133-L134

does not anticipate `num_batches < 500`.
