### ISSUE TITLE
RuntimeError in the Transformer during texture sampling

### ISSUE THREAD

**Issue by jbueltemeier** [pmeier/pystiche#139]
`RuntimeError: Given groups=1, weight of size 8 6 3 3, expected input[1, 3, 10, 10] to have 6 channels, but got 3 channels instead`

The transformer has too many channels for input, this is probably because in `UlyanovEtAl2016NoiseModule` the `out_channels` will always be 6 unless explicitly entered `in_channels`. However, since no `in_channels` exist in texture sampling and the `in_channels` are not set explicitly, this error occurs. 

I also noticed that the noise is not on the right `device`. Currently another error occurs if the above error is bypassed and `device="cuda"` is set. 
```python
from pystiche.papers.ulyanov_et_al_2016.modules import UlyanovEtAl2016Transformer
import torch
impl_params = True
instance_norm = False
stylization = False
levels = 6
transformer = UlyanovEtAl2016Transformer(
        levels,
        impl_params=impl_params,
        instance_norm=instance_norm,
        stylization=stylization,
    )
device = "cuda"
input_image = torch.rand(1, 3, 256, 256).to(device)
transformer.to(device)
transformer(input_image)
```

**Comment by pmeier** [comment]
Thanks for the report. 

---

For the next time: you can still simplify your example and get to the same error:

```python
from pystiche.papers.ulyanov_et_al_2016.modules import UlyanovEtAl2016Transformer
import torch


transformer = UlyanovEtAl2016Transformer(levels=1, stylization=False,)
device = "cuda"
input_image = torch.rand(1, 3, 256, 256).to(device)
transformer.to(device)
transformer(input_image)
```

By looking at your example my first impression was that the error occurs only

-  `if impl_params and not instance_norm` and
- `if levels == 6`

which is, as it turned out, not the case.
