### ISSUE TITLE
Execution stops 

### ISSUE THREAD

**Issue by Barbarosse** [pmeier/pystiche#229]
When I execute the code stops in this stat forever :  

```
I'm working with pystiche==0.4.0+dev
I'm working with cuda
PerceptualLoss(
  (content_loss): FeatureReconstructionOperator(
    encoder=MultiLayerVGGEncoder(layer=relu4_2, arch=vgg19, weights=torch)
  )
  (style_loss): MultiLayerEncodingOperator(
    encoder=MultiLayerVGGEncoder(arch=vgg19, weights=torch), score_weight=2
    (relu3_1): MRFOperator(score_weight=0.5, patch_size=(3, 3), stride=(2, 2))
    (relu4_1): MRFOperator(score_weight=0.5, patch_size=(3, 3), stride=(2, 2))
  )
)
ImagePyramid(
  (0): PyramidLevel(edge_size=300, num_steps=200, edge=short)
  (1): PyramidLevel(edge_size=550, num_steps=200, edge=short)
)
```

**Comment by pmeier** [comment]
Please clarify a few things for me please:

- I'm guessing you are talking about the [`ImagePyramid` example](https://pystiche.readthedocs.io/en/latest/galleries/examples/advanced/example_image_optimization_with_pyramid.html), correct?

- What do you mean by 

  > stops in this stat[e] forever

  ? Does the code terminate? If yes, what is the error message?

- Guessing from output you got the problem happens after the `ImagePyramid` is created. Did the images get shown to you? If you are working with `matplotlib.pyplot` the execution stops until you close the figure window.

**Comment by Barbarosse** [comment]
Thank you pmeier ! 
Question 1 : I'm guessing you are talking about the ImagePyramid example, correct?
Answer 1 : It occur with "ImagePyramid" and "nst_with_pystiche" examples, wheras nst_without_pystiche works fine.

Question 2 ; What do you mean by "stops in this stat[e] forever"
Answer 2 : the stay at the output I gave above.

Question 3: Does the code terminate? If yes, what is the error message?
Answer 3: The code does not terminate. 

Yes the content image shows up and still opened.

**Comment by pmeier** [comment]
> the content image shows up and stays open.

You need to close it to resume execution. The examples are meant to be run as notebooks where you want to look at the images. 

If you just want to run them from beginning to start I recommend you comment out all lines with  `show_image()`. 

The same applies to all `print`s: while this works if run as script, the output is meaningless without the text around it.

**Comment by Barbarosse** [comment]
It did the job. Thanks.
