### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Barbarosse** [pmeier/pystiche#244]
When the script is run more than once it return the following error : 
`RuntimeError: CUDA out of memory`

**Comment by pmeier** [comment]
Please be more specific:

- Which script are you running?
- At what point does the error occur?
- What does 
  > run more than once
  
  mean? Are you running it multiple times within the same process? If so, how?

**Comment by Barbarosse** [comment]
I think the problem is due to the lack of gpu memory when I tried to increase the size of the image. 
I have 4GB of memory isn't it enough to double the default size (500) ?

**Comment by pmeier** [comment]
> I have 4GB of memory isn't it enough to double the default size (500) ?

Nope. Memory usage grows linear with the number of pixels which in turn grows quadratic with respect to the size. That means, if you double the size you need approximately 4 times the amount of memory. 

In #220 I'm working on showing the memory requirement for each example.
